# ===================================================================
# Spring Boot 会自动扫描 classpath 下的 application.yml 文件，如果有就加载文件配置
#
# Spring Boot 中多环境配置文件名需要满足 application-{profile}.yml 的格式，{profile} 对应你的环境标识
# 本地环境 application-local.yml
# 开发环境 application-dev.yml
# 测试环境 application-test.yml
# 生产环境 application-prod.yml
# 多环境配置文件激活属性
# 本地环境 local
# 开发环境 dev
# 测试环境 test
# 生产环境 prod
# ===================================================================

spring:

  # 应用名称配置
  application:
    name: project

  # 多环境配置
  profiles:
    active: dev

  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 1024MB # 单个文件大小
      max-request-size: 1024MB # 设置总上传的文件大小

# 监控端点配置
management:
  server:
    port: 8085

# 服务器配置
server:
  port: 8088

# 文档生成配置
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  swagger-ui:
    enabled: true

  api-docs:
    enabled: true
